version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1.29.0
parameters:
  # how many test machines to run in parallel?
  PARALLEL_TESTS:
    type: integer
    default: 2
# https://circleci.com/docs/2.0/executor-intro/
executors:
  # create our own executor with Cypress dependencies
  # and specific resource class
  test-container:
    # https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: medium+
    docker:
      # this Docker image is built by the Cypress team and is tagged with Node version
      # https://github.com/cypress-io/cypress-docker-images
      - image: 'cypress/base:17.8.0'
workflows:
  build:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install:
          executor: test-container
          build: 'npm run build'
      - cypress/run:
          requires:
            - cypress/install
          executor: test-container
          start: 'npm run server:ci' # start server before running tests
          wait-on: 'http://localhost:1234'
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: << pipeline.parameters.PARALLEL_TESTS >>
          group: 'all tests' # name this group "all tests" on the dashboard
          tags: 'circleci'
